"""add DatabaseInfo column status

Revision ID: 27cdca62c2b6
Revises: 
Create Date: 2017-04-02 13:10:36.359499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27cdca62c2b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis', 'dbinfo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('analysis', 'dbinfo_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text(u"''"))
    op.alter_column('analysis', 'original_sql',
               existing_type=mysql.VARCHAR(length=2000),
               nullable=True,
               existing_server_default=sa.text(u"''"))
    op.alter_column('analysis', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.add_column('database_info', sa.Column('status', sa.Integer(), nullable=True))
    op.alter_column('database_info', 'db_host',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text(u"''"))
    op.alter_column('database_info', 'db_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text(u"''"))
    op.alter_column('database_info', 'db_port',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text(u"'3306'"))
    op.alter_column('database_info', 'db_pwd',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text(u"''"))
    op.alter_column('database_info', 'db_user',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text(u"''"))
    op.alter_column('database_info', 'item_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text(u"''"))
    op.alter_column('database_info', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text(u"''"))
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True,
               existing_server_default=sa.text(u"''"))
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text(u"''"))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text(u"''"))
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False,
               existing_server_default=sa.text(u"''"))
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text(u"''"))
    op.alter_column('database_info', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('database_info', 'item_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text(u"''"))
    op.alter_column('database_info', 'db_user',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text(u"''"))
    op.alter_column('database_info', 'db_pwd',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text(u"''"))
    op.alter_column('database_info', 'db_port',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text(u"'3306'"))
    op.alter_column('database_info', 'db_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text(u"''"))
    op.alter_column('database_info', 'db_host',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text(u"''"))
    op.drop_column('database_info', 'status')
    op.alter_column('analysis', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('analysis', 'original_sql',
               existing_type=mysql.VARCHAR(length=2000),
               nullable=False,
               existing_server_default=sa.text(u"''"))
    op.alter_column('analysis', 'dbinfo_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text(u"''"))
    op.alter_column('analysis', 'dbinfo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
